version: '3'
services:
  database:
    image: postgres
    ports:
    - 6432:5432
    environment:
      POSTGRES_DB: glumon
      POSTGRES_USER: glumon
      POSTGRES_PASSWORD: glumon
  service:
    build: .
    ports:
    - 9090:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database/glumon
      SPRING_DATASOURCE_USERNAME: glumon
      SPRING_DATASOURCE_PASSWORD: glumon
    depends_on:
    - database