server:
  port: 8080
spring:
  application:
    name: overseer
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: ${REDIS_HOSTNAME}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  jackson:
    deserialization:
      fail-on-unknown-properties: true
    
com:
  behl:
    overseer:
      unsecured:
        api-path:
          swagger-v3: true
          post:
            - /api/v1/user
            - /api/v1/auth/login
          get:
            - /api/v1/plan 
      token:
        secret-key: ${JWT_SECRET_KEY}
        validity: 30
      open-api:
        api-version: 1.0.0
        title: Overseer
        description: Backend application imposing rate limit on private API endpoints using token bucket algorithm