name: Rate limiting APIs using token bucket algorithm build

on:
  push:
    branches: [ "main", "feature/*", "fix/*", "refactor/*" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check-out repository
      uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'adopt'
        cache: maven
    - name: Set up Docker
      uses: docker/setup-buildx-action@v3
    - name: Compile project
      run: mvn compile
    - name: Run unit tests
      run: mvn test
    - name: Run integration tests
      run: mvn integration-test verify
