name: Rate limiting APIs using token bucket algorithm build

on:
  push:
    branches: [ "master", "feature/*", "fix/*", "refactor/*" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check-out repository
      uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'adopt'
        cache: maven
    - name: Compile project
      run: mvn compile
